const PDFDocument = require('pdfkit');
const { PDFDocument: PDFLibDoc } = require('pdf-lib');
const fs = require('fs').promises;

/**
 * PDF Service for SalesHUB
 * Generates A4 documents with editable form fields and high-quality images
 */
class PDFService {
  constructor() {
    this.pageSize = 'A4';
    this.dpi = 300; // High quality
  }

  /**
   * Generate PDF with form fields
   */
  async generate(template, data, settings = {}) {
    // Create PDF document
    const doc = new PDFDocument({
      size: settings.pageSize || 'A4',
      margins: {
        top: settings.margins?.top || 20,
        bottom: settings.margins?.bottom || 20,
        left: settings.margins?.left || 20,
        right: settings.margins?.right || 20
      },
      layout: template.layout || 'portrait',
      info: {
        Title: `${data.projectName || 'SalesHUB Document'}`,
        Author: 'SalesHUB',
        Subject: 'Real Estate Sales Offer'
      }
    });

    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));

    // === BRAND HEADER ===
    if (settings.branding?.logo) {
      try {
        const logoBuffer = await this.getImageBuffer(settings.branding.logo);
        doc.image(logoBuffer, 20, 20, {
          width: settings.branding.logoWidth || 100,
          quality: 100 // No compression
        });
      } catch (err) {
        console.warn('Could not load logo:', err.message);
      }
    }

    if (settings.branding?.companyName) {
      doc.fontSize(18)
         .fillColor(settings.branding.primaryColor || '#1a365d')
         .text(settings.branding.companyName, settings.branding.logoWidth + 30 || 130, 25);
    }

    // === DOCUMENT TITLE ===
    doc.fontSize(16)
       .fillColor('#000000')
       .text(data.title || 'SALES OFFER', { align: 'center' })
       .moveDown(0.5);

    // Add horizontal line
    doc.moveTo(20, doc.y)
       .lineTo(doc.page.width - 20, doc.y)
       .strokeColor('#e2e8f0')
       .stroke()
       .moveDown(0.5);

    // === PROPERTY DETAILS SECTION ===
    doc.fontSize(14)
       .fillColor('#1a365d')
       .text('Property Details', { underline: true })
       .moveDown(0.3);

    this.renderPropertyDetails(doc, data);

    // === FINANCIAL BREAKDOWN ===
    doc.addPage();
    doc.fontSize(14)
       .fillColor('#1a365d')
       .text('Financial Breakdown', { underline: true })
       .moveDown(0.3);

    this.renderFinancialBreakdown(doc, data);

    // === PAYMENT PLAN (for Off-Plan) ===
    if (data.category === 'Off-Plan Resale' && data.paymentPlan?.length > 0) {
      doc.addPage();
      doc.fontSize(14)
         .fillColor('#1a365d')
         .text('Payment Plan', { underline: true })
         .moveDown(0.3);

      this.renderPaymentPlan(doc, data.paymentPlan);
    }

    // === FLOOR PLANS ===
    if (data.floorPlans?.length > 0) {
      doc.addPage();
      doc.fontSize(14)
         .fillColor('#1a365d')
         .text('Floor Plans', { underline: true })
         .moveDown(0.3);

      for (const plan of data.floorPlans) {
        try {
          const imageBuffer = await this.getImageBuffer(plan.path);
          doc.image(imageBuffer, 20, doc.y, {
            width: doc.page.width - 40,
            quality: 100 // No compression
          });
          if (plan.label) {
            doc.fontSize(10)
               .fillColor('#4a5568')
               .text(plan.label, { align: 'center' });
          }
          doc.moveDown(0.5);
        } catch (err) {
          console.warn('Could not load floor plan:', err.message);
        }
      }
    }

    // === FOOTER ===
    const totalPages = doc.bufferedPageRange().count;
    for (let i = 0; i < totalPages; i++) {
      doc.switchToPage(i);
      doc.fontSize(9)
         .fillColor('#718096')
         .text(
           `Page ${i + 1} of ${totalPages} | Generated by SalesHUB`,
           20,
           doc.page.height - 20,
           { align: 'center' }
         );
    }

    doc.end();

    return new Promise((resolve) => {
      doc.on('end', () => {
        resolve(Buffer.concat(chunks));
      });
    });
  }

  /**
   * Render property details section
   */
  renderPropertyDetails(doc, data) {
    const details = [
      { label: 'Project Name', value: data.projectName },
      { label: 'Unit Number', value: data.unitNumber },
      { label: 'Category', value: data.category },
      { label: 'Unit Type', value: data.unitType },
      { label: 'View', value: data.view },
      { label: 'Status', value: data.status }
    ];

    doc.fontSize(11);

    // Two-column layout
    const colWidth = (doc.page.width - 60) / 2;
    let col = 0;

    details.forEach(detail => {
      if (col === 0 && detail.value) {
        doc.fillColor('#4a5568').text(`${detail.label}:`, 20, doc.y, { width: colWidth });
        doc.fillColor('#000000').text(detail.value || '-', 20, doc.y, { width: colWidth });
      } else if (detail.value) {
        doc.fillColor('#4a5568').text(`${detail.label}:`, 30 + colWidth, doc.y - 16, { width: colWidth });
        doc.fillColor('#000000').text(detail.value || '-', 30 + colWidth, doc.y - 16, { width: colWidth });
        col = 0;
      } else {
        col = 0;
      }
    });

    // Areas section
    doc.moveDown(0.5);
    doc.fontSize(11)
       .fillColor('#1a365d')
       .text('Areas', { underline: false })
       .moveDown(0.2);

    const areas = this.getAreaFields(data.category, data.unitType);
    areas.forEach(area => {
      if (data[area.field]) {
        doc.fillColor('#4a5568')
           .text(`${area.label}:`, 20, doc.y, { width: 150 });
        doc.fillColor('#000000')
           .text(`${data[area.field]} sq.ft`, 170, doc.y - 11, { width: 150 });
      }
    });
  }

  /**
   * Render financial breakdown
   */
  renderFinancialBreakdown(doc, data) {
    const financials = [
      { label: 'Unit Price (AED)', value: this.formatCurrency(data.unitPrice) },
      { label: 'ADGM Fee (4%)', value: this.formatCurrency(data.adgmFee) },
      { label: 'Agency Fee (2% + VAT)', value: this.formatCurrency(data.agencyFee) },
      { label: 'Premium (if applicable)', value: this.formatCurrency(data.premium) },
      { label: 'Total Amount', value: this.formatCurrency(data.totalAmount), highlight: true }
    ];

    // Table header
    doc.fontSize(10)
       .fillColor('#4a5568');

    // Rows
    let y = doc.y;
    financials.forEach((item, index) => {
      if (item.value) {
        if (item.highlight) {
          doc.rect(20, y - 5, doc.page.width - 40, 25)
             .fillColor('#e2e8f0')
             .fill();
          doc.fillColor('#1a365d');
        } else {
          doc.fillColor('#000000');
        }

        doc.fontSize(item.highlight ? 12 : 10)
           .text(item.label, 25, y);
        doc.text(item.value, doc.page.width - 180, y);
        y += 25;
      }
    });
  }

  /**
   * Render payment plan table
   */
  renderPaymentPlan(doc, paymentPlan) {
    const tableTop = doc.y;
    const colWidths = [60, 200, 150, 150];
    const rowHeight = 25;

    // Header
    doc.fontSize(10)
       .fillColor('#1a365d');

    const headers = ['#', 'Milestone', 'Due Date', 'Amount (AED)'];
    headers.forEach((header, i) => {
      const x = 20 + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
      doc.text(header, x, tableTop, { width: colWidths[i] });
    });

    // Rows
    doc.fontSize(9).fillColor('#000000');

    paymentPlan.forEach((milestone, rowIndex) => {
      const y = tableTop + rowHeight + (rowIndex * rowHeight);

      // Alternating row background
      if (rowIndex % 2 === 0) {
        doc.rect(20, y, doc.page.width - 40, rowHeight)
           .fillColor('#f7fafc')
           .fill();
      }

      const row = [
        (rowIndex + 1).toString(),
        milestone.description,
        milestone.dueDate || 'Upon Booking',
        this.formatCurrency(milestone.amount)
      ];

      row.forEach((cell, cellIndex) => {
        const x = 20 + colWidths.slice(0, cellIndex).reduce((a, b) => a + b, 0);
        doc.fillColor('#000000').text(cell, x + 5, y + 5, { width: colWidths[cellIndex] - 10 });
      });
    });

    // Total
    const total = paymentPlan.reduce((sum, m) => sum + (parseFloat(m.amount) || 0), 0);
    const lastRowY = tableTop + rowHeight + (paymentPlan.length * rowHeight) + 10;

    doc.rect(20, lastRowY, doc.page.width - 40, rowHeight)
       .fillColor('#1a365d')
       .fill();

    doc.fillColor('#ffffff')
       .text('Total Payment Plan', 25, lastRowY + 5, { width: colWidths.slice(0, 2).reduce((a, b) => a + b, 0) });
    doc.text(this.formatCurrency(total), doc.page.width - 180, lastRowY + 5);
  }

  /**
   * Get area fields based on category and unit type
   */
  getAreaFields(category, unitType) {
    if (category === 'Plot') {
      return [
        { field: 'plotSize', label: 'Plot Size' },
        { field: 'allowedBuildArea', label: 'Allowed Build Area' }
      ];
    }

    if (unitType?.includes('Villa') || unitType?.includes('Townhouse')) {
      return [
        { field: 'internalArea', label: 'Internal Area' },
        { field: 'terraceArea', label: 'Terrace Area' },
        { field: 'bua', label: 'BUA' },
        { field: 'gfa', label: 'GFA' },
        { field: 'plotSize', label: 'Plot Size' }
      ];
    }

    return [
      { field: 'internalArea', label: 'Internal Area' },
      { field: 'balconyArea', label: 'Balcony Area' }
    ];
  }

  /**
   * Format currency
   */
  formatCurrency(value) {
    if (!value) return '-';
    return `AED ${parseFloat(value).toLocaleString('en-AE', { minimumFractionDigits: 2 })}`;
  }

  /**
   * Get image buffer from base64 or URL
   */
  async getImageBuffer(source) {
    if (source.startsWith('data:image')) {
      const base64Data = source.split(',')[1];
      return Buffer.from(base64Data, 'base64');
    }

    if (source.startsWith('http')) {
      const response = await fetch(source);
      return Buffer.from(await response.arrayBuffer());
    }

    return await fs.readFile(source);
  }

  /**
   * Generate preview image for live preview
   */
  async generatePreview(template, data, settings) {
    // For preview, we can use html2canvas on the existing preview element
    // This is called from backend but can delegate to client-side for speed
    throw new Error('Preview should be generated client-side for better performance');
  }
}

module.exports = new PDFService();
